routes/web.php
<?php

use App\Http\Controllers\NotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('productos', ProductController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/publicacion', [PublicationController::class, 'index'])->name('publication.index');

// Route::group(['middleware' => ['role:Autor']], function () {
Route::group(['middleware' => ['auth:sanctum']], function () {
    //rutas accesibles solo para admin
    Route::get('/', function () {
        return view('home');
    })->name('home');

    Route::resource('publicacion', PublicationController::class)->parameters(['publicacion' => 'publication']);

    Route::group(['middleware' => ['role:Administrador|Bibliotecario']], function () {
        Route::get('notificaciones', [NotificationController::class, 'index'])->name('notification.index');
    });
    
    Route::group(['middleware' => ['role:Administrador']], function () {
        Route::resource('usuarios', UserController::class)->parameters([
            'usuarios' => 'user'
        ]);
        Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
        Route::get('roles/editar/{role}', [RoleController::class, 'edit'])->name('roles.edit');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['nombre', 'categoria', 'precio'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductoRequest;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductoRequest $request)
    {
        /* $request->validate([
            'nombre' => 'required',
            'categoria' => 'required',
            'precio' => 'required'
        ], [
            'nombre.required' => 'El campo nombre es obligatorio',
            'categoria.required' => 'El campo categoria es obligatorio',
            'precio.required' => 'El campo precio es obligatorio'
        ]); */

        Product::create([
            'nombre' => $request->nombre,
            'categoria' => $request->categoria,
            'precio' => $request->precio
        ]);
        return redirect()->route('productos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $producto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $producto)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductoRequest $request, Product $producto)
    {
        $producto->nombre = $request->nombre;
        $producto->categoria = $request->categoria;
        $producto->precio = $request->precio;
        $producto->save();
        return redirect()->route('productos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $producto)
    {
        $producto->delete();
        return redirect()->route('productos.index');
    }
}

resources/views/product/create.blade.php
@extends('layout.master')

@section('contenido')
    <div class="card mt-5">
        <div class="card-header">
            Crear Producto
        </div>
        <form action="{{ route('productos.store') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col form-group">
                        <label for="nombre">Nombre:</label>
                        <input class="form-control" type="text" name="nombre" id="nombre" value="{{ old('nombre') }}">
                    </div>
                    <div class="col form-group">
                        <label for="categoria">Categoria:</label>
                        <input class="form-control" type="text" name="categoria" id="categoria" value="{{ old('categoria') }}">
                    </div>
                    <div class="col form-group">
                        <label for="precio">Precio:</label>
                        <input class="form-control" type="number" name="precio" id="precio" value="{{ old('precio') }}">
                    </div>
                    <div class="col align-self-end">
                        <button class="btn btn-primary">
                            Guardar
                        </button>
                    </div>
                </div>
                <div class="row">
                    @if ($errors->any())
                        <div class="alert alert-danger mt-4" role="alert">
                            @foreach ($errors->all() as $error)
                                <p>
                                    {{ $error }}
                                </p>
                            @endforeach
                        </div>
                    @endif
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layout.master')

@section('contenido')
    <div class="card mt-5">
        <div class="card-header">
            Crear Producto
        </div>
        <form action="{{ route('productos.update') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col form-group">
                        <label for="nombre">Nombre:</label>
                        <input class="form-control" type="text" name="nombre" id="nombre" value="{{ old('nombre') }}">
                    </div>
                    <div class="col form-group">
                        <label for="categoria">Categoria:</label>
                        <input class="form-control" type="text" name="categoria" id="categoria" value="{{ old('categoria') }}">
                    </div>
                    <div class="col form-group">
                        <label for="precio">Precio:</label>
                        <input class="form-control" type="number" name="precio" id="precio" value="{{ old('precio') }}">
                    </div>
                    <div class="col align-self-end">
                        <button class="btn btn-primary">
                            Guardar
                        </button>
                    </div>
                </div>
                <div class="row">
                    @if ($errors->any())
                        <div class="alert alert-danger mt-4" role="alert">
                            @foreach ($errors->all() as $error)
                                <p>
                                    {{ $error }}
                                </p>
                            @endforeach
                        </div>
                    @endif
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layout.master')

@section('contenido')
    <div class="card mt-5">
        <div class="card-header">
            Lista Productos
        </div>
        <div class="card-body">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Categoría</th>
                        <th>Precio</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr>
                            <td>{{ $product->nombre }}</td>
                            <td>{{ $product->categoria }}</td>
                            <td>${{ number_format($product->precio, 2) }}</td>
                            <td>
                                <a class="btn btn-sm btn-success" href="{{ route('productos.show', $product) }}">Editar</a>
                                <form class="d-inline" action="{{ route('productos.destroy', $product) }}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-danger">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection