routes/web.php
<?php

use App\Http\Controllers\NotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('productos', ProductController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/publicacion', [PublicationController::class, 'index'])->name('publication.index');

// Route::group(['middleware' => ['role:Autor']], function () {
Route::group(['middleware' => ['auth:sanctum']], function () {
    //rutas accesibles solo para admin
    Route::get('/', function () {
        return view('home');
    })->name('home');

    Route::resource('publicacion', PublicationController::class)->parameters(['publicacion' => 'publication']);

    Route::group(['middleware' => ['role:Administrador|Bibliotecario']], function () {
        Route::get('notificaciones', [NotificationController::class, 'index'])->name('notification.index');
    });
    
    Route::group(['middleware' => ['role:Administrador']], function () {
        Route::resource('usuarios', UserController::class)->parameters([
            'usuarios' => 'user'
        ]);
        Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
        Route::get('roles/editar/{role}', [RoleController::class, 'edit'])->name('roles.edit');
    });
});

app/Http/Controllers/PublicationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Publication;
use Illuminate\Http\Request;

class PublicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('publication.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('publication.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Publication  $publication
     * @return \Illuminate\Http\Response
     */
    public function show(Publication $publication)
    {
        return view('publication.show', compact('publication'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Publication  $publication
     * @return \Illuminate\Http\Response
     */
    public function edit(Publication $publication)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Publication  $publication
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Publication $publication)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Publication  $publication
     * @return \Illuminate\Http\Response
     */
    public function destroy(Publication $publication)
    {
        //
    }
}

app/Http/Livewire/Nav/Notification.php
<?php

namespace App\Http\Livewire\Nav;

use Livewire\Component;
use App\Models\Publication;
use Illuminate\Support\Facades\Auth;

class Notification extends Component
{
    public $notifications = [];

    protected $listener = ['loadNotifications'];

    public function mount()
    {
        foreach(Auth::user()->unreadNotifications as $notification)
        {
            array_push($this->notifications, $notification->data['publication_id']);
        }
        $this->notifications = Publication::whereIn('id', $this->notifications)->latest()->get();
    }

    public function loadNotifications()
    {
        $this->dispatchBrowserEvent('countNotifications', ['count' => Auth::user()->unreadNotifications()->count()]);
        return true;
    }
    public function render()
    {
        return view('livewire.nav.notification');
    }
}

app/Http/Livewire/Publication/Comment.php
<?php

namespace App\Http\Livewire\Publication;

use App\Models\Comment as ModelsComment;
use App\Models\Publication;
use Livewire\Component;

class Comment extends Component
{
    public $comment;
    public $publication;

    protected $listeners = ['setPublicationId'];

    protected $rules = [
        'comment' => 'required'
    ];

    protected $messages = [
        'comment.required' => 'Debe dejar un texto de comentario.'
    ];

    public function setPublicationId(Publication $publication)
    {
        $this->publication = $publication;
    }

    public function addComment()
    {
        $this->validate();

        ModelsComment::create([
            'user_id' => auth()->user()->id,
            'publication_id' => $this->publication->id,
            'comment' => $this->comment
        ]);

        $this->emitTo('publication.show', 'comments');

        $this->dispatchBrowserEvent('alert', ['title' => $this->publication->title]);

        $this->comment = '';
    }

    public function render()
    {
        return view('livewire.publication.comment');
    }
}

app/Http/Livewire/Publication/Create.php
<?php

namespace App\Http\Livewire\Publication;

use App\Models\Publication;
use App\Models\Type;
use App\Providers\Published;
use Livewire\Component;

class Create extends Component
{
    public $title;
    public $description;
    public $types = [];
    public $type=1;
    public $typeForm;
    public $publication=null;

    public $action='<i class="fas fa-fw fa-plus"></i> Crear';
    public $a='crear';

    public $listeners = ['openModal'];

    protected $rules = [
        'title' => 'required',
        'description' => 'required|min:25'
    ];

    protected $messages = [
        'title.required' => 'Debe escribir un título.',
        'description.required' => 'Debe escribir una descripción',
        'description.min' => 'La descripción debe ser mínimo de 25 caracteres.'
    ];

    public function mount()
    {
        $this->types = Type::all();
    }

    public function openModal($title, $id)
    {
        if($id)
        {
            $this->publication = Publication::find($id);
            $this->title = $this->publication->title;
            $this->description = $this->publication->description;
            $this->type = $this->publication->type_id;
        }

        if($title == "Editar Publicación")
        {
            $this->action = '<i class="fas fa-fw fa-save"></i> Guardar';
            $this->a = 'edit';
        }else{
            $this->action = '<i class="fas fa-fw fa-plus"></i> Crear';
            $this->a = 'create';
            
            $this->title = '';
            $this->description = '';
            $this->type = 1;
            $this->publication=null;
        }
        $this->dispatchBrowserEvent('openModal', ['title' => $title]);
    }

    public function create()
    {
        $this->validate();
        $publication = Publication::create([
            'title' => $this->title,
            'description' => $this->description,
            'user_id' => auth()->user()->id,
            'state' => 'Publicado',
            'type_id' => $this->type
        ]);

        event(new Published($publication));

        $this->dispatchBrowserEvent('alert', [
            'title' => 'Publicación Creada',
            'msg' => "Se ha creado correctamente la publicación <strong>{$this->title}</strong>",
            'icon' => 'success'
        ]);

        $this->emitTo('publication.index', 'publications');
        $this->emitTo('nav.notification', 'loadNotifications');

        $this->title = '';
        $this->description = '';
        $this->type = '';
    }

    public function edit()
    {
        $this->publication->title = $this->title;
        $this->publication->description = $this->description;
        $this->publication->type_id = $this->type;
        $this->publication->save();
        
        $this->dispatchBrowserEvent('alert', [
            'title' => 'Publicación Editada',
            'msg' => "Se ha editado correctamente la publicación <strong>{$this->title}</strong>",
            'icon' => 'success'
        ]);
        $this->emitTo('publication.index', 'publications');
    }

    public function render()
    {
        return view('livewire.publication.create');
    }
}

app/Http/Livewire/Publication/Edit.php
<?php

namespace App\Http\Livewire\Publication;

use Livewire\Component;

class Edit extends Component
{
    public function render()
    {
        return view('livewire.publication.edit');
    }
}

app/Http/Livewire/Publication/Index.php
<?php

namespace App\Http\Livewire\Publication;

use Livewire\Component;
use App\Models\Publication;
use Illuminate\Support\Facades\Auth;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $queryString = [
        'search' => ['except' => '']
    ];
    public $search='';

    protected $listeners = ['publications'];

    public function publications()
    {
        return true;
    }

    public function openModal($title, $id=null)
    {
        $this->emitTo('publication.create', 'openModal', $title, $id);
    }
    
    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function delete($id)
    {
        $publication = Publication::find($id);
        if(Auth::user()->can('Eliminar Publicacion') && ($publication->user_id == Auth::user()->id))
        {
            $publication->delete();
        }else{
            $this->dispatchBrowserEvent('alert', [
                'title' => 'Error',
                'html' => 'No tiene permisos para eliminar esta publicación',
                'icon' => 'error'
            ]);
        }
    }

    public function render()
    {
        $publications = Publication::when(!empty($this->search), function($q){
            $q->where('title', 'REGEXP', $this->search)
                ->orWhere('description', 'REGEXP', $this->search)
                ->orWhereHas('user', function($query){
                    return $query->where('name', 'REGEXP', $this->search);
                });
        })->when(auth()->user()->hasRole('Usuario'), function($q){
            $q->where('state', 'Disponible');
        })->latest()->paginate(5);
        
        return view('livewire.publication.index', compact('publications'));
    }
}

app/Http/Livewire/Publication/Show.php
<?php

namespace App\Http\Livewire\Publication;

use App\Models\Publication;
use Livewire\Component;

class Show extends Component
{
    public $publication;

    protected $listeners = ['comments'];

    public function sendId()
    {
        $this->emitTo('publication.comment', 'setPublicationId', $this->publication);
    }

    public function comments()
    {
        return true;
    }

    public function render()
    {
        $this->comments();
        return view('livewire.publication.show');
    }
}

app/Http/Livewire/User/Create.php
<?php

namespace App\Http\Livewire\User;

use App\Models\User;
use Livewire\Component;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;

class Create extends Component
{
    public $name;
    public $email;
    public $role;
    public $user;
    public $password;

    protected $listeners = ['setUser'];

    protected $rules = [
        'name' => 'required',
        'email' => 'required|email',
        'role' => 'required'
    ];

    protected $messages = [
        'name.required' => 'Los nombres son obligatorios.',
        'email.required' => 'El correo es obligatorio.',
        'email.email' => 'El correo no tiene un formato válido.',
        'role.required' => 'Debe elegir un rol.'
    ];

    public function updatingName()
    {
        $this->name = strtolower($this->name);
        $this->name = ucwords($this->name);
    }

    public function setUser($user)
    {
        if($user == 'create')
        {
            $this->user = $user;
            $this->name = '';
            $this->email = '';
            $this->role = 1;
            $this->dispatchBrowserEvent('changeTitle', ['title' => 'Crear Usuario']);
            return true;
        }else{
            $this->dispatchBrowserEvent('changeTitle', ['title' => 'Editar Usuario']);
        }
        $this->user = User::find($user);
        $this->name = $this->user->name;
        $this->email = $this->user->email;
        $this->role = $this->user->roles()->first()->id;
    }

    public function save()
    {
        $this->validate();
        if($this->user !== 'create')
        {
            $this->user->name = $this->name;
            $this->user->email = $this->email;
            if(!empty($this->password))
            {
                $this->user->password = Hash::make($this->password);
            }
            $this->user->removeRole($this->user->roles()->first()->name);
            $this->user->assignRole(Role::findOrFail($this->role));
            // $this->user->save();
            $this->user->update();
            $this->dispatchBrowserEvent('alert', [
                'title' => 'Usuario editado!',
                'message' => 'Se han realizado los cambios correctamente.',
                'icon' => 'success',
                'cerrar' => true
            ]);
        }else{
            if(empty($this->password)){
                $this->dispatchBrowserEvent('alert', [
                    'title' => 'Error al crear',
                    'message' => 'Debe digitar una contraseña',
                    'icon' => 'error'
                ]);
                return true;
            }
            $user = User::create([
                'name' => $this->name,
                'email' => $this->email,
                'password' => Hash::make($this->password),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ]);

            $user->assignRole(Role::findOrFail($this->role));

            $this->dispatchBrowserEvent('alert', [
                'title' => 'Usario creado!',
                'message' => 'Se ha creado el usuario correctamente.',
                'icon' => 'success',
                'cerrar' => true
            ]);
        }
        
    }
    
    public function render()
    {
        return view('livewire.user.create', [
            'roles' => Role::all()
        ]);
    }
}

app/Http/Livewire/User/Index.php
<?php

namespace App\Http\Livewire\User;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class Index extends Component
{
    public $search;

    public function sendUser($user)
    {
        $this->emitTo('user.create', 'setUser', $user);
    }

    public function delete($id)
    {
        $user = User::find($id);
        $user->delete();
    }

    public function render()
    {
        if(!empty($this->search))
        {
            $users = User::where('name', 'LIKE', "%{$this->search}%")
                ->orWhere('email', 'LIKE', "%{$this->search}%")
                ->get();
        }else{
            $users = User::where('id', '<>', Auth::user()->id)->get();
        }
        return view('livewire.user.index', [
            'users' => $users
        ]);
    }
}

app/Http/Livewire/User/Role/Edit.php
<?php

namespace App\Http\Livewire\User\Role;

use Livewire\Component;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class Edit extends Component
{
    public Role $role;
    public $permissions;

    public function mount()
    {
        $this->permissions = Permission::get();
    }

    public function assignPermission(Permission $permission)
    {
        if(!$this->role->hasPermissionTo($permission->name)){
            $this->role->givePermissionTo($permission->name);
        }else{
            $this->role->revokePermissionTo($permission->name);
        }
    }

    public function render()
    {
        return view('livewire.user.role.edit');
    }
}

app/Http/Livewire/User/Role/Index.php
<?php

namespace App\Http\Livewire\User\Role;

use Livewire\Component;
use Spatie\Permission\Models\Role;

class Index extends Component
{
    public $roles;
    public $search;

    public function render()
    {
        $this->roles = Role::when(!empty($this->search), function($q) {
            $q->where('name', 'LIKE', "%{$this->search}%");
        })->get();
        return view('livewire.user.role.index');
    }
}

resources/views/livewire/publication/comment.blade.php
<div>
    <form wire:submit.prevent='addComment' method="POST">
        <div class="row">
            <div class="col form-group">
                <label for="comment">
                    <strong>
                        {{ $publication->title ?? '' }}
                    </strong>
                </label>
                <textarea wire:model='comment' class="form-control"></textarea>
                @error('comment')
                    <div class="text-danger">
                            {{ $message }}
                    </div>
                 {{-- <span class="error">{{ $message }}</span> --}}
                @enderror
            </div>
        </div>
        <div class="row mt-2">
            <div class="col form-group">
                <button class="btn btn-secondary">
                    <i class="fas fa-fw fa-plus"></i> Agregar
                </button>
            </div>
        </div>
    </form>
</div>

@push('js')
    <script>
        window.addEventListener('alert', event => {
            Swal.fire(
                'Comentario guardado',
                'Se ha comentado la publicación ' + event.detail.title,
                'success'
            );
            modalComment.hide();
        });
    </script>
@endpush

resources/views/livewire/publication/create.blade.php
<div>
    <form wire:submit.prevent="{{ $a }}">
        <div class="row">
            <div class="col-3 col-md-6 col-sm-6 form-group">
                <label for="title">Titulo</label>
                <input wire:model='title' type="text" class="form-control">
                @error('title')
                    <div class="text-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="col-2 col-md-6 col-sm-6 form-group">
                <label for="type">Tipo</label>
                <select wire:model="type" id="type" class="form-select">
                    @foreach ($types as $t)
                        <option value="{{ $t->id }}">{{ $t->type }}</option>
                    @endforeach
                </select>
                @error('type')
                    <div class="text-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </div>
        <div class="row">
            <div class="col form-group">
                <label for="description">Descripción</label>
                <textarea wire:model='description' type="text" class="form-control h-20" rows="20"></textarea>
            </div>
            @error('description')
                <div class="text-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="row mt-2">
            <div class="col form-group">
                <button class="btn btn-secondary" id="btnActionPublication">
                    {!! $action !!}
                </button>
            </div>
        </div>
    </form>
</div>
@push('js')
    <script>
        document.addEventListener('DOMContentLoaded', ()=>{
            
        });

        window.addEventListener('openModal', event => {
            if(event.detail.title == "Editar Publicación")
            {
                document.getElementById('createPublicationTitle').innerHTML = '<i class="fas fa-book"></i> ' + event.detail.title;
                // document.getElementById('btnActionPublication').innerHTML = '<i class="fas fa-fw fa-save"></i> Guardar';
                modalCreate.show();
            }else{
                document.getElementById('createPublicationTitle').innerHTML = '<i class="fas fa-book"></i> ' + event.detail.title;
                // document.getElementById('btnActionPublication').innerHTML = '<i class="fas fa-fw fa-plus"></i> Crear';
                modalCreate.show();
            }
        });

        window.addEventListener('alert', event => {
            Swal.fire({
                title: event.detail.title,
                html: event.detail.msg,
                icon: event.detail.icon
            });
            if(modalCreate)
            {
                modalCreate.hide()
            }
        });
    </script>
@endpush

resources/views/livewire/publication/edit.blade.php
<div>
    {{-- Do your work, then step back. --}}
</div>

resources/views/livewire/publication/index.blade.php
<div>
    <h1 class="app-page-title">
        <i class="fas fa fa-book"></i>
        Publicaciones
    </h1>
    <div class="app-card app-card-orders-table">
        <div class="app-card-body">
            <div class="row mb-2 p-3">
                <div class="col-3 form-group">
                    <label class="form-label" for="search">
                        <i class="fas fa-fw fa-search"></i>
                        <strong>Buscar...</strong>
                    </label>
                    <input wire:model="search" type="search" class="form-control">
                </div>
                @can('Publicar')    
                    <div class="col-2 form-group align-self-end">
                        <button wire:click="openModal('Nueva Publicación')" type="button" class="btn app-btn-primary">
                            <i class="fas fa-plus"></i> Crear
                        </button>
                    </div>
                @endcan
            </div>
            <div class="table-responsive p-3">
                <table class="table app-table-hover">
                    <thead>
                        <tr>
                            <th class="cell">Titulo</th>
                            <th class="cell">Descripción</th>
                            <th class="cell">Autor</th>
                            <th class="cell">Tipo</th>
                            <th class="cell">Estado</th>
                            <th class="cell">Publicado</th>
                            <th class="cell text-center" style="white-space:nowrap;">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($publications as $publication)
                            <tr>
                                <td class="align-middle">{{ $publication->title }}</td>
                                <td class="align-middle">{{ $publication->description }}</td>
                                <td class="align-middle">{{ $publication->user->name }}</td>
                                <td class="align-middle">{{ $publication->type->type }}</td>
                                <td class="align-middle"> 
                                    <span class="{{ $publication->badge }}">
                                    {{ $publication->state }}
                                    </span>
                                </td>
                                <td class="align-middle" style="white-space:nowrap;">
                                    {{-- {{ $publication->created_at->format('d/m/Y'); }} --}}
                                    {{ $publication->created_at->diffForHumans(); }}
                                </td>
                                @auth    
                                    <td class="align-middle" style="white-space:nowrap;">
                                        <a class="btn btn-sm btn-info text-white" href="{{ route('publicacion.show', $publication) }}">
                                            <i class="fas fa-info-circle"></i>
                                        </a>

                                        @if (Auth::user()->can('Editar Publicacion') && ($publication->user_id == Auth::user()->id)) 
                                            <button wire:click="openModal('Editar Publicación', {{ $publication->id }})" class="btn btn-sm app-btn-primary">
                                                <i class="fas fa-edit"></i>
                                            </button>
                                        @endif

                                        @if (Auth::user()->can('Eliminar Publicacion') && ($publication->user_id == Auth::user()->id))
                                            <button class="btn btn-sm btn-danger text-white" onclick="delPublication({{ $publication->id }}, '{!! $publication->titleHTML !!}', '{{ $publication->state }}')">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        @endif
                                    </td>
                                @endauth
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $publications->links() }}
            </div>
        </div>
    </div>
</div>

@push('js')
    <script>
        const delPublication = (publication_id, publication_title, publication_state)=>{
            Swal.fire({
                title: '¿Estás seguro?',
                html: `Está acción eliminará la publicación <strong>${publication_title}</strong> seleccionada!`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, borrar!',
                cancelButtonText: 'Cancelar',
                }).then((result) => {
                if (result.isConfirmed) {
                    if(publication_state == 'Préstamo') {
                        Swal.fire({
                            title: 'Upps!',
                            html: `No puedes eliminar la publicación <strong>${publication_title}</strong> ya que se encuentra en préstamo.`,
                            icon: 'error',
                        });
                    }else{
                        @this.delete(publication_id)
                        Swal.fire({
                            title: 'Eliminada!',
                            html: `Has eliminado la publicación <strong>${publication_title}.</strong>`,
                            icon: 'success',
                        });
                    }
                }
            });
        };

        window.addEventListener('alert', event=>{
            Swal.fire({
                title: event.detail.title,
                html: event.detail.html,
                icon: event.detail.icon
            });
        });
    </script>
@endpush